#!/bin/sh

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  List hiding elements:"
  echo "    hiding [TERM...]"
  echo "      list active tasks hiding specified contexts/projects"
  echo ""
  exit
}

[ "$action" = "hiding" ] && {
    if [ ! -z $@ ]; then
	FILTER_COMMAND="grep -v $(echo $@ | sed 's/\s/|/g')"
    fi
    TODOTXT_FINAL_FILTER=$FILTER_COMMAND bash $TODO_SH ls
}

